### ISSUE TITLE
WebRTC-based transport

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-core#15]
Considering the browser side cannot use createServer() to create arbitrary listening server ports, could we use WebRTC as a transport method (at least a fallback transport)?  That way, you could connect two browser-based clients together without a non-browser intermediary.

**Comment by arj03** [comment]
Yeah that would be super sweet to support. Especially since it just works on LAN I've heard

**Comment by KyleMaas** [comment]
What would be the proper way (and place) to add this?

**Comment by KyleMaas** [comment]
Looks like maybe it would be best to add a plugin to ssb-js/multiserver?

**Comment by KyleMaas** [comment]
Might be easier than I thought, if I can get multiserver-dht working on Hyperswarm:

https://github.com/RangerMauve/hyperswarm-web

**Comment by arj03** [comment]
Yeah that hyperswarm web looks really nice. Adding it as a multiserver plugin should work, then you should have full api of the remote node on connection.
