### ISSUE TITLE
Allow core-based projects to add plugins to the stack

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-core#38]
Would be nice if there was some way for core-based projects to tack on other plugins to the stack during initialization.  That way, adding the Threads tab in ssb-browser-demo wouldn't have required a change to core.

**Comment by arj03** [comment]
Yes, will fix that together with the singleton

**Comment by arj03** [comment]
Fixed. See README for extra or browser-demo.

**Comment by KyleMaas** [comment]
Liking that solution a lot.
