### ISSUE TITLE
a question -- how to get a list of connections

### ISSUE THREAD

**Issue by nichoth** [arj03/ssb-browser-core#51]
How does one get a list of everything you are connected to? rooms & pubs & local peers if applicable (i'm not sure how ssb-browser-core does it).

**Comment by arj03** [comment]
Have a look at [connections](https://github.com/arj03/ssb-browser-demo/blob/master/ui/connections.js) in browser-demo. Basically it just uses the API from ssb-conn (SSB.net.conn).

**Comment by nichoth** [comment]
Thanks @arj03 . So in `conn`, there is [this recipe](https://github.com/staltz/ssb-conn#recipes) for getting all currently connected peers. And a peer in this context means someone we are connected to directly, vs a 'pub', which you connect to but just relays messages from peers. 

Does the browser version of ssb have the concept of invites & pubs, or is it just 'rooms'?

**Comment by arj03** [comment]
conn: yes

It supports pubs and rooms and also "direct" connections over DHT. Invites are not supported as I'm of the opinion that they don't make sense in SSB main. They might make sense if you use a different cap, but that is a different story. So I'm not against adding it, just havn't seen a good use case.
