### ISSUE TITLE
Room connection string needs to strip off .ed25519 from the end of the room's ID

### ISSUE THREAD

**Issue by KyleMaas** [arj03/ssb-browser-core#70]
Can't seem to connect to other clients through `go-ssb-room`.  I can connect to the room just fine, but when I try to connect to another attached SSB client, I get the following connection error:

```
{
    "type": "connecting-failed",
    "address": "tunnel:@[[room ID]].ed25519.ed25519:@[[other client ID]].ed25519~shs:[[client ID]]",
    "key": "@[[client ID]].ed25519",
    "details": {
        "message": "could not connect to:tunnel:@[[room ID]].ed25519.ed25519:@[[other client ID]].ed25519~shs:[[other client ID]], only know:net~shs;ws~shs;ws~noauth;tunnel~shs",
        "stack": [[way too long to include]]
    }
}
```

There are a couple odd things about this:

1. The room ID part has two instances of `.ed25519` in it.
2. It seems to do the same thing whether I try to connect to a Patchwork, Manyverse, or another `ssb-browser-demo` client.

**Comment by KyleMaas** [comment]
Okay, nevermind.  After I wrote this out I realized that maybe the extra `.ed25519` was coming from the room connection string.  I tried removing that, and it worked fine.

However, that probably ought to be stripped off the end of room connect strings.  So I think I'm going to change the title of this issue so others don't run into the same problem.

**Comment by arj03** [comment]
sounds good

**Comment by arj03** [comment]
This doesn't seem to be a bug in ssb-browser-core but rather one of the underlying libraries, like ssb-conn or similar.

**Comment by KyleMaas** [comment]
@arj03

Since you have a better idea of where this should be filed than I do, can you file this upstream please?  One way or another, it's still a problem that ought to be fixed.
