### ISSUE TITLE
Error while install deps

### ISSUE THREAD

**Issue by frankiebee** [arj03/ssb-browser-core#71]
during the setup of this project i run `npm install` and run into this err: (this allso occurs when installing `yarn add ssb-browser-core` as a dependency) 

npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! node:internal/errors:484
npm ERR!     ErrorCaptureStackTrace(err);
npm ERR!     ^
npm ERR! 
npm ERR! Error: spawn nj-cli ENOENT
npm ERR!     at ChildProcess._handle.onexit (node:internal/child_process:285:19)
npm ERR!     at onErrorNT (node:internal/child_process:483:16)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
npm ERR!   errno: -2,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'spawn nj-cli',
npm ERR!   path: 'nj-cli',
npm ERR!   spawnargs: [ 'build', '--release' ]
npm ERR! }
npm ERR! 
npm ERR! Node.js v19.0.0

**Comment by frankiebee** [comment]
isee its because of ssb-validate2-rsjs-node

**Comment by arj03** [comment]
Oh right, that dependency can be a pain to install. I have a PR I was working on to [upgrade db2](https://github.com/arj03/ssb-browser-core/pull/68). In the latest version we don't use ssb-validate2-rsjs-node anymore. I should probably get that finished :)

**Comment by arj03** [comment]
@frankiebee I have release v14. Could you give it a try and see if that is better? At least [browser-example](https://github.com/arj03/ssb-browser-example) seems to be working :)

**Comment by frankiebee** [comment]
It install now! thank you! and thanks for getting back so quickly!
